### ISSUE TITLE
Potentially adding a license?

### ISSUE THREAD

**Issue by rymanb** [Vieper1/MemoryManager#1]
Hello, I'm working on my own game engine and have been researching implementations for memory managers that I could put into my own personal engine project. I like your design using a combination of FSA and linear pool allocation and was thinking of making a derivative of this design for my project. However there is currently no license for this project, so I was wondering if would be possible to add a license so that this would be possible for me to do, if not I totally understand. 
Thanks and all the best!

**Comment by Vieper1** [comment]
Hi Ryman,

(Not sure if you'll receive this email)
Thank you for reaching out to me.
I'm glad you liked the design!

I'll be sure to add a license to that project when I get back next week.


Best!

**Comment by Vieper1** [comment]
Just added a license to the repo
